# Конфигурация Samba для раздачи MergerFS пула в сеть
[Media-Storage]
   path = /mnt/media_pool
   browseable = yes
   read only = no
   guest ok = no
   create mask = 0777
   directory mask = 0777
   force user = root

[Downloads-Temp]
   path = /mnt/disk_temp
   browseable = yes
   read only = no
   guest ok = no
   create mask = 0777
   directory mask = 0777
   force user = root
