apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false

  - name: OpenSearch-Logs
    type: grafana-opensearch-datasource
    access: proxy
    url: http://127.0.0.1:9200
    database: "homelab-*"
    jsonData:
      version: "2.11.0"
      flavor: "opensearch"
      timeField: "@timestamp"
    editable: false
